# --- Sample dataset

# --- !Ups

insert into company (id,name) values (  DEFAULT,'Apple Inc.');
insert into company (id,name) values (  DEFAULT,'Thinking Machines');
insert into company (id,name) values (  DEFAULT,'RCA');
insert into company (id,name) values (  DEFAULT,'Netronics');
insert into company (id,name) values (  DEFAULT,'Tandy Corporation');
insert into company (id,name) values (  DEFAULT,'Commodore International');
insert into company (id,name) values (  DEFAULT,'MOS Technology');
insert into company (id,name) values (  DEFAULT,'Micro Instrumentation and Telemetry Systems');
insert into company (id,name) values (  DEFAULT,'IMS Associates, Inc.');
insert into company (id,name) values ( DEFAULT,'Digital Equipment Corporation');
insert into company (id,name) values ( DEFAULT,'Lincoln Laboratory');
insert into company (id,name) values ( DEFAULT,'Moore School of Electrical Engineering');
insert into company (id,name) values ( DEFAULT,'IBM');
insert into company (id,name) values ( DEFAULT,'Amiga Corporation');
insert into company (id,name) values ( DEFAULT,'Canon');
insert into company (id,name) values ( DEFAULT,'Nokia');
insert into company (id,name) values ( DEFAULT,'Sony');
insert into company (id,name) values ( DEFAULT,'OQO');
insert into company (id,name) values ( DEFAULT,'NeXT');    
insert into company (id,name) values ( DEFAULT,'Atari');
insert into company (id,name) values ( DEFAULT,'Acorn computer');
insert into company (id,name) values ( DEFAULT,'Timex Sinclair');
insert into company (id,name) values ( DEFAULT,'Nintendo');
insert into company (id,name) values ( DEFAULT,'Sinclair Research Ltd');
insert into company (id,name) values ( DEFAULT,'Xerox');
insert into company (id,name) values ( DEFAULT,'Hewlett-Packard');
insert into company (id,name) values ( DEFAULT,'Zemmix');
insert into company (id,name) values ( DEFAULT,'ACVS');
insert into company (id,name) values ( DEFAULT,'Sanyo');
insert into company (id,name) values ( DEFAULT,'Cray');
insert into company (id,name) values ( DEFAULT,'Evans & Sutherland');    
insert into company (id,name) values ( DEFAULT,'E.S.R. Inc.');
insert into company (id,name) values ( DEFAULT,'OMRON');
insert into company (id,name) values ( DEFAULT,'BBN Technologies');
insert into company (id,name) values ( DEFAULT,'Lenovo Group');
insert into company (id,name) values ( DEFAULT,'ASUS');
insert into company (id,name) values ( DEFAULT,'Amstrad');
insert into company (id,name) values ( DEFAULT,'Sun Microsystems');
insert into company (id,name) values ( DEFAULT,'Texas Instruments');
insert into company (id,name) values ( DEFAULT,'HTC Corporation');
insert into company (id,name) values ( DEFAULT,'Research In Motion');
insert into company (id,name) values ( DEFAULT,'Samsung Electronics');

insert into computer (id,name,introduced,discontinued,company_id) values (  DEFAULT,'MacBook Pro 15.4 inch',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  DEFAULT,'CM-2a',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  DEFAULT,'CM-200',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  DEFAULT,'CM-5e',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  DEFAULT,'CM-5','1991-01-01',null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  DEFAULT,'MacBook Pro','2006-01-10',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  DEFAULT,'Apple IIe',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  DEFAULT,'Apple IIc',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  DEFAULT,'Apple IIGS',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Apple IIc Plus',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Apple II Plus',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Apple III','1980-05-01','1984-04-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Apple Lisa',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'CM-2',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Connection Machine','1987-01-01',null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Apple II','1977-04-01','1993-10-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Apple III Plus','1983-12-01','1984-04-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'COSMAC ELF',null,null,3);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'COSMAC VIP','1977-01-01',null,3);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'ELF II','1977-01-01',null,4);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh','1984-01-24',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh II',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh Plus','1986-01-16','1990-10-15',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh IIfx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'iMac','1998-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Mac Mini','2005-01-22',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Mac Pro','2006-08-07',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Power Macintosh','1994-03-01','2006-08-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'PowerBook','1991-01-01','2006-01-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Xserve',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Powerbook 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Powerbook 140',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Powerbook 170',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'PowerBook Duo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'PowerBook 190',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh Quadra','1991-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh Quadra 900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh Quadra 700',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh LC','1990-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh LC II','1990-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh LC III','1993-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh LC III+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh Quadra 605','1993-10-21',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh LC 500 series',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'TRS-80 Color Computer','1980-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Acorn System 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Dragon 32/64',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'MEK6800D2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Newbear 77/68',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Commodore PET',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Commodore 64','1982-08-01','1994-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Commodore 64C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Commodore SX-64',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Commodore 128',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Apple I','1976-04-01','1977-10-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'KIM-1','1975-01-01',null,7);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Altair 8800','1974-12-19',null,8);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'IMSAI 8080','1975-08-01',null,9);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'IMSAI Series Two',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'VAX','1977-10-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'VAX 11/780','1977-10-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'VAX 11/750','1980-10-01',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'TX-2','1958-01-01',null,11);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'TX-0','1956-01-01',null,11);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Whirlwind','1951-04-20',null,11);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'ENIAC','1946-02-15','1955-10-02',12);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'IBM PC','1981-08-12',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh Classic',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh Classic II','1991-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Amiga','1985-01-01',null,14);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Amiga 1000',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Amiga 500','1987-01-01',null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Amiga 500+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Amiga 2000','1986-01-01','1990-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Amiga 3000',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Amiga 600','1992-03-01',null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh 128K','1984-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh 512K','1984-09-10','1986-04-14',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh SE','1987-03-02','1989-08-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Macintosh SE/30','1989-01-19','1991-10-21',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Canon Cat','1987-01-01',null,15);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Nokia 770',null,null,16);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Nokia N800','2007-01-01',null,16);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Mylo','2006-09-21',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'OQO 02','2007-01-01',null,18);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'OQO 01+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Pinwheel calculator',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'iBook',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'MacBook','2006-05-16',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'NeXTstation','1990-01-01','1993-01-01',19);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'NeXTcube','1988-01-01','1993-01-01',19);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'NeXTstation Color Turbo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'NeXTstation Color',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'NeXTstation Turbo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'NeXTcube Turbo',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'NeXTcube 040',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'NeXTcube 030',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Tinkertoy Tic-Tac-Toe Computer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( DEFAULT,'Z3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Z4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Z1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Z2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Wang 2200','1973-05-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Wang VS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Wang OIS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'BBC Micro',null,null,22);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM 650','1953-01-01','1962-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray-1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray-3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray-2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray-4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray X1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray XD1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray T3D','1993-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray T3E','1995-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray C90',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray T90',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray SV1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray J90',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray XT3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray CS6400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari ST','1985-01-01','1993-01-01',20);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 2500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 2500',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 4000',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 3000UX',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 3000T',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 4000T',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 1200','1992-10-01','1996-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 1040 STf','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 520 ST','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 520 STfm','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 1040 STe','1989-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari MEGA STe','1991-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 520 ST+','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 520 STm','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 130 ST','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 260 ST','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari MEGA ST','1987-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 520 STf','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 1040 STfm','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 2080 ST','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 260 ST+','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 4160 STe','1988-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'TRS-80 Color Computer 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'TRS-80 Color Computer 3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'TRS-80 Model 1','1977-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Timex Sinclair 2068','1983-11-01','1984-04-01',23);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ZX Spectrum','1982-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Xerox Star','1981-01-01',null,26);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Xerox Alto',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Acorn Archimedes',null,null,22);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Nintendo Entertainment System',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Super Nintendo Entertainment System','1991-08-01','1999-01-01',24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Super Famicom',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Nintendo GameCube',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Game Boy line',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PlayStation','1994-12-03',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PlayStation 2','2000-03-24',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Game & Watch',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'EDSAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM System/4 Pi',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM AP-101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM TC-1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM AP-101B',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM AP-101S',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ProLiant',null,null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Http://nepomuk.semanticdesktop.org/xwiki/',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sinclair QL','1984-01-01','1986-01-01',25);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sinclair ZX81','1981-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sinclair ZX80',null,null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 65XE',null,null,20);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Deep Blue',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Quadra 650',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Quadra 610',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Quadra 800',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Quadra 950',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 160',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 145B',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 170',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 145',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 140',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh IIcx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Powerbook 180',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook G4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh XL',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 2400c',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 1400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Quadra 630',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Quadra 660AV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Quadra 840AV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 5300',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 3400c',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Color Classic',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh 512Ke',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh IIsi',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh IIx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 500 series',null,null,null);


# --- !Downs

delete from computer;
delete from company;
