# --- Sample dataset

# --- !Ups

insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh IIci',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'iMac G5','2004-08-31',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Mac G4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 7100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 9600',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 7200',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 7300',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 8600',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 6200',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 8100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Compact Macintosh',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 4400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 9500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Portable',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'EMac',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 7600',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Mac G5',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 7500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 6100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 8500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh IIvi',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh IIvx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IMac G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IMac G4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Mac G4 Cube',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Intel iMac',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Deep Thought',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Wii','2006-11-19',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM System x',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM System i','2006-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM System z','2006-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM System p','2000-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'LC 575',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh TV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh Performa',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh II series',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 6400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 6500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Apple PenLite',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Wallstreet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Twentieth Anniversary Macintosh',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 5500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'iBook G3',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 5200 LC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh 5400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'CM-1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MSX','1983-01-01','1995-01-01',28);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PlayStation 3',null,null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MSX2','1986-01-01',null,29);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MSX2+','1988-01-01',null,30);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MSX turbo R','1990-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Panasonic FS A1GT',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Panasonic FS A1ST',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-11',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-1',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-10',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-8',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-6',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DECSYSTEM-20',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-7',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-5',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-12',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'LINC',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-14',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-15',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PDP-16',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray X2','2007-01-01',null,31);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Cray X-MP','1982-01-01',null,31);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Evans & Sutherland ES-1',null,null,32);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Commodore VIC-20','1980-01-01',null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerBook 150',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MacBook Air','2008-01-15',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Digi-Comp I','1963-01-01',null,33);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Digi-Comp',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Digi-Comp II',null,null,33);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Manchester Mark I','1949-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Small-Scale Experimental Machine','1948-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Nintendo 64',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Game Boy Advance',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Game Boy',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Nintendo DS Lite',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Nintendo DS','2004-01-01',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Game Boy Color',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Game Boy Advance SP',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Virtual Boy',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Game Boy Micro',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Roadrunner',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HP 9000',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'OMRON Luna-88K2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'OMRON Luna-88K',null,null,34);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Motorola series 900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Motorola M8120',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Triton Dolphin System 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'BBN TC2000','1989-08-01',null,35);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'WRT54G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ThinkPad','1992-01-01',null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Apple Newton','1993-01-01','1998-01-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atanasoff-Berry Computer','1937-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atlas Computer','1962-01-01','1974-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASUS Eee PC 901',null,null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASUS Eee PC 701',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM 7030','1961-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'System/38','1979-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'System/36','1983-01-01','2000-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM 7090','1959-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM RT',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'System/360','1964-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM 801','1980-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM 1401','1959-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASCI White','2001-01-01','2006-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Blue Gene',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASCI Blue Pacific','1998-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'iPhone','2007-06-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Nokia N810','2007-10-17',null,16);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'EDSAC 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Titan',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Pilot ACE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HP Mini 1000','2008-10-29',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HP 2133 Mini-Note PC','2008-04-15',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Kogan Agora Pro','2008-12-04',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'D-Series Machines',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ZX Spectrum 48K','1982-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ZX Spectrum 16K','1982-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ZX Spectrum 128','1985-09-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ZX Spectrum +3',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ZX Spectrum +2','1986-01-01',null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ZX Spectrum +2A','1987-01-01',null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ZX Spectrum +','1984-06-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Acer Extensa',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Acer Extensa 5220',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Dell Latitude',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Toshiba Satellite',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Timex Sinclair 2048',null,null,23);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sprinter',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Timex Computer 2048',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Pentagon',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Belle',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Loki',null,null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Hobbit',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'NeXT Computer',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'TRS-80',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'TRS-80 Model 2','1980-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'TRS-80 Model 3',null,null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'STacy','1989-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ST BOOK','1990-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari 520 STE','1989-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 2000 Model A',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 2000 Model B',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 2000 Model C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM 3270',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'CALDIC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Modbook',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Compaq SystemPro',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ARRA',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM System Cluster 1350',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Finite element machine',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ES7000',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HP MediaSmart Server',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HP Superdome',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM Power Systems','2008-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Oslo Analyzer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Microsoft Softcard',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'WITCH',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Analytical engine',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'EDVAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'BINAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Earth Simulator',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'BARK',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Harvard Mark I','1944-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ILLIAC IV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ILLIAC II',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ILLIAC III',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Water integrator',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'CSIRAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'System X',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Harvest',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ChipTest',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HiTech',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Bomba',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ACE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASCI Red',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASCI Thors Hammer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASCI Purple','2005-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASCI Blue Mountain',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Columbia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HP Integrity',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'APEXC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Datasaab D2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'BRLESC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DYSEAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'SSEC','1948-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Hydra',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'FUJIC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'RAYDAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Harvard Mark III',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DATAR',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ReserVec',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DASK',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'UTEC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DRTE Computer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PowerEdge',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Apple Network Server',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Goodyear MPP',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Macintosh 128K technical details',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Power Macintosh G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'CER-10',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'CER-20',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM BladeCenter','2002-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Wisconsin Integrally Synchronized Computer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amstrad CPC',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amstrad CPC 6128',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amstrad CPC 664',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amstrad CPC 464',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Intergraph',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Enterprise',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MTX500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Acorn Electron',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sony Vaio P','2009-02-01',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'VAIO',null,null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sony Vaio P VGN-P588E/Q',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sony Vaio P VGN-P530H/G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sony Vaio P VGN-P530H/W',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sony Vaio P VGN-P530H/Q',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sony Vaio P VGN-P530H/R',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sony Vaio P VGN-P588E/R',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sony Vaio P VGN-P598E/Q',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Timex Sinclair 1000','1982-07-01',null,23);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Komputer 2086',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Galaksija',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Vector-06C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Elektronika BK',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sun386i',null,null,39);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Xerox Daybreak','1985-01-01','1989-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Xerox NoteTaker',null,null,26);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'D4a','1965-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'LGP-30',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'LGP-21',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASUS Eee PC 900','2008-05-01',null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Atari TT030',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Bi Am ZX-Spectrum 48/64',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Bi Am ZX-Spectrum 128',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PlayStation Portable',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MSI Wind Netbook',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sharp Mebius NJ70A','2009-04-21',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HTC Snap',null,null,41);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Commodore Educator 64',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Amiga 1500',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Commodore 65',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Commodore 16',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Commodore CBM-II',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Commodore Plus/4',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Commodore LCD',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Commodore MAX Machine',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Aster CT-80',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Test','2009-01-01','2009-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MSI GX723',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Eee PC 1000HV','2009-05-22',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'VTech Laser 200','1983-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'CrunchPad',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Neo Geo','1990-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sega Mega Drive',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sega Master System',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'TurboGrafx-16',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Sun-3',null,null,39);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Pleiades',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM Sequoia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Inves Spectrum 48k plus',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'iPhone 3G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'iPhone 3GS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Beagle Board',null,null,40);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HP nPar',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MacBook Family',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Reservisor',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'BladeSystem',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad t60p',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad x200',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad t60',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad w700',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad t41',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad z61p',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad x61s',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad t43',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad r400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad x60s',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad x301',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad t42',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad r61',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad w500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad sl400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad x40',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad x200 tablet',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'lenovo thinkpad t400s',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Nokia N900','2009-10-01',null,16);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Internet Tablet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Meiko Computing Surface','1986-01-01','1993-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'CS-2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM 701','1952-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM 5100','1975-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'AN/FSQ-7','1958-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'AN/FSQ-32','1960-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM CPC','1949-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'System/34','1978-01-01','1983-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'System/32','1975-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'System/3','1969-01-01','1985-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IBM 305','1956-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'English Electric DEUCE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'CER-203',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'CER-22',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Kentucky Linux Athlon Testbed',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'QNAP TS-101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'iPad','2010-01-01','2011-03-02',1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'iPhone 2G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Inslaw',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'WePad','2010-07-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MacBook Parts',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240LL/A) DDR2 Model',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240T/A) DDR2 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240X/A) DDR2 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MacBook 13-inch Core 2 Duo 2.26GHz (Unibody MC207LL/A) DDR3 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MC240LL/A',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'D.K.COMMUNICATION',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'iPhone 4',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Nintendo 3DS','2010-03-23',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ASUS Eee PC 1005PE','2010-01-01',null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'National Law Enforcement System',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'BlackBerry PlayBook',null,null,42);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Barnes & Noble nook','2009-10-20',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'SAM Coupé',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HTC Dream','2008-10-22',null,41);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Samsung Galaxy Tab','2010-09-02',null,40);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'BlackBerry PlayBook','2010-09-27',null,42);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Tianhe-I',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Kno',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ThinkPad 701 C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ThinkPad 340 CSE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ThinkPad 755 CX',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ThinkPad 755 CE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ThinkPad 370 C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Coleco Adam','1983-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Nebulae',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Alex eReader',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Acer Iconia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Archos 101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Fujitsu Lifebook T900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Motorola Xoom',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ViewSonic G Tablet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC Professional','1982-01-01',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC Multia','1994-11-07',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC Firefly',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC 3000 AXP',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC 2000 AXP','1993-05-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC 4000 AXP','1992-11-10',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC 7000/10000 AXP','1992-11-10',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC Professional 350',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC Rainbow 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC Professional 325',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DECmate II',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DECmate',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DECsystem',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'NetApp Filer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'DEC GT40',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'ecoATM',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'MindWave BrainCubed Education Bundle',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'PalmPilot',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Upcoming iPhone 5',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Dell Inspiron 560 Desktop Computer ',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'IPad 2',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HP TouchPad','2011-02-09',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'HP Veer','2011-02-09',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Lenovo Thinkpad Edge 11',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Dell Vostro',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'Gateway LT3103U','2008-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (DEFAULT,'iPhone 4S','2011-10-14',null,1);

# --- !Downs

delete from computer where id > 250;
